from .equipment import Equipment
# Imports the 'Equipment' class from the 'equipment' module.
# This line is crucial because it establishes the inheritance relationship, allowing the Turbine class
# to extend and utilize the functionalities already defined in Equipment.


class Turbine(Equipment):
    # Defines the Turbine class as a subclass of Equipment.
    # Inheritance is indicated by '(Equipment)' after the class name.

    def __init__(self, name):
        # This is the constructor of the Turbine class. It is executed whenever you create a new turbine.
        # 'name' is the argument you will use to name this specific turbine instance.

        super().__init__(name)
        # Calls the constructor of the parent class (Equipment) using 'super()'.
        # This is fundamental to ensure that all basic equipment attributes,
        # such as the name, the lists of input and output connectors, and the 'heat' and 'work' attributes,
        # are correctly initialized.

        self.heat = 0.0
        # Overrides the 'heat' attribute (heat) which was initialized as None in Equipment,
        # setting it to 0.0. Turbines are often modeled as **adiabatic**,
        # which means that heat exchange with the environment is considered negligible during operation.

    def calculate(self):
        # This method defines the specific calculation logic for a turbine.
        # It will be responsible for determining the work generated by the turbine.

        self.work = - self.enthalpy_balance
        # Assigns the value of work ('self.work') to the negative of the enthalpy balance
        # ('self.enthalpy_balance').

        # 'self.enthalpy_balance' is calculated by the 'energy_balance' method (inherited from Equipment)
        # as (H_out - H_in).
        # For a turbine, which expands a fluid and generates work, the fluid's enthalpy decreases,
        # i.e., H_out < H_in. This results in a negative 'enthalpy_balance'.

        # The First Law of Thermodynamics for a steady-state control volume,
        # with negligible heat and kinetic/potential energy changes, is:
        # Q - W = DeltaH
        # If Q = 0 (adiabatic turbine), then -W = DeltaH, which implies W = -DeltaH.
        # Here, 'W' represents the work done *by* the system.
        # Since the 'enthalpy_balance' (DeltaH) is negative for a turbine,
        # 'self.work' (which is -DeltaH) will be positive, indicating work done *by* the system,
        # which is consistent with the function of a turbine.